version: 2
jobs:
  build:
    working_directory: ~/build
    docker:
      - image: $REGISTRY_URL/circleci-base:alpine-latest
        aws_auth:
          aws_access_key_id: $AWS_ACCESS_KEY_ID
          aws_secret_access_key: $AWS_SECRET_ACCESS_KEY
    steps:
      - checkout
      - setup_docker_engine
      - run:
          name: Build and push docker image
          command: |
            APP=${CIRCLE_PROJECT_REPONAME}
            TAG=${CIRCLE_SHA1:0:7}

            $(aws ecr get-login --no-include-email --region eu-central-1)

            docker build -t ${REGISTRY_URL}/${APP}:${TAG} .
            docker push ${REGISTRY_URL}/${APP}:${TAG}
            docker tag ${REGISTRY_URL}/${APP}:${TAG} ${REGISTRY_URL}/${APP}:latest
            docker push ${REGISTRY_URL}/${APP}:latest
